# Generated by Django 2.0.2 on 2018-04-02 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180402_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
